name: "Push to Cachix"
on:
    push:
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - uses: cachix/install-nix-action@v12
        - uses: cachix/cachix-action@v8
          with:
              name: monte
              signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
