name: "IRC Notice"
on:
    pull_request:
    push:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: push
              uses: rectalogic/notify-irc@v1
              if: github.event_name == 'push'
              with:
                  channel: "#monte"
                  nickname: monte-notify-irc
                  message: |
                      ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
                      ${{ join(github.event.commits.*.message, ' ') }}
            - name: pr
              uses: rectalogic/notify-irc@v1
              if: github.event_name == 'pull_request'
              with:
                  channel: "#monte"
                  nickname: monte-notify-irc
                  message: |
                      ${{ github.actor }} ${{ github.event.action }} PR ${{ github.event.number }}
