name: "IRC Notice"
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: push
              uses: rectalogic/notify-irc@v1
              if: github.event_name == 'push'
              with:
                  channel: "#monte"
                  nickname: monte-notify-irc
                  message: |
                      ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
                      ${{ join(github.event.commits.*.message) }}
